### PR TITLE
Simplify autotune.php WEB_CONCURRENCY output a bit more

### LINKED ISSUE #689: PHP-FPM Worker Process Configuration Error, Fractional Worker Count Issue
Hi,
After New formula for determining number of PHP-FPM worker processes updates creating issue with the php code deploy to server.
PHP-FPM Initialization Failure Due to Invalid Worker Process,
Syntax error occurring in the PHP-FPM configuration file, where a value for the number of worker processes (pm.max_children) is expected but is not provided in a valid format.
Additionally, the error points out an attempt to use a fractional value (e.g., 4.5 workers), which is not supported as the number of worker processes must be a whole number.
FPM configration file.
php_value[memory_limit] = 2048M
php_value[max_execution_time] = 300
request_terminate_timeout = 350

Sharing some logs that i am facing:
```
Start of container output (web.5)        
DOCUMENT_ROOT changed to '..../'        
Using PHP-FPM configuration include 'fpm_custom.conf'        
Available RAM is 9007199254740988K Bytes        
Number of CPU cores is 1        
 PHP memory_limit is 2048M Bytes        
vendor/bin/heroku-php-apache2: line 434: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")        
Starting php-fpm with 4.5 workers...        
ERROR: [/conf/php/8/php-fpm.conf :258] unable to parse value for entry 'pm.max_children': is not a valid number (greater or equal than zero)        
ERROR: failed to load configuration file '/conf/php/8/php-fpm.conf'        
ERROR: FPM initialization failed        
Process exited unexpectedly: php-fpm, shutting down...        
Shutdown complete.        
DOCUMENT_ROOT changed to '.../'        
Using PHP-FPM configuration include 'fpm_custom.conf'        
Available RAM is 9007199254740988K Bytes        
Number of CPU cores is 1        
PHP memory_limit is 2048M Bytes        
vendor/bin/heroku-php-apache2: line 434: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")        
Starting php-fpm with 4.5 workers...        
ERROR: [./conf/php/8/php-fpm.conf :258] unable to parse value for entry 'pm.max_children': is not a valid number (greater or equal than zero)        
ERROR: failed to load configuration file './conf/php/8/php-fpm.conf'        
ERROR: FPM initialization failed        
Process exited unexpectedly: php-fpm, shutting down...        
Shutdown complete.        
DOCUMENT_ROOT changed to '.../'        
Using PHP-FPM configuration include 'fpm_custom.conf'        
Available RAM is 9007199254740988K Bytes        
Number of CPU cores is 1        
PHP memory_limit is 2048M Bytes        
/heroku-php-apache2: line 434: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")        
Starting php-fpm with 4.5 workers...        
ERROR: [./conf/php/8/php-fpm.conf :258] unable to parse value for entry 'pm.max_children': is not a valid number (greater or equal than zero)        
ERROR: failed to load configuration file './conf/php/8/php-fpm.conf'        
ERROR: FPM initialization failed        
Process exited unexpectedly: php-fpm, shutting down...        
Shutdown complete.        
DOCUMENT_ROOT changed to '/'        
Using PHP-FPM configuration include 'fpm_custom.conf'        
Available RAM is 9007199254740988K Bytes        
Number of CPU cores is 1        
PHP memory_limit is 2048M Bytes        
/heroku-php-apache2: line 434: [[: 4.5: syntax error: invalid arithmetic operator (error token is ".5")        
Starting php-fpm with 4.5 workers...        
ERROR: [./conf/php/8/php-fpm.conf:258] unable to parse value for entry 'pm.max_children': is not a valid number (greater or equal than zero)        
ERROR: failed to load configuration file './conf/php/8/php-fpm.conf'        
ERROR: FPM initialization failed        
Process exited unexpectedly: php-fpm, shutting down...        
Shutdown complete.        
2024/02/06 13:19:32 signal: terminated
```

### PR DESCRIPTION
**Pull request by dzuelke**
For consistency with previous versions of the buildpack, and to reduce potential for confusion (think e.g. number of cores on shared dynos), the CPU core count is now only printed in verbose mode or when there is no `${DYNO}` env var.

However, should the log_2 CPU core count based `WEB_CONCURRENCY` limit kick in, a notice is now always printed.

Also adds `-h/--help` switches, and different verbosity levels.

Related to #685 and #684.

Fixes #689.

GUS-W-14634717

### CODE REVIEW

**Comment by dzuelke** [comment]
Output examples (all with `memory_limit = 128M`).

1X dyno:
```
Available RAM is 512M Bytes
PHP memory_limit is 128M Bytes
```

Container with 512M Bytes RAM and 8 CPU cores:
```
Available RAM is 512M Bytes
Number of CPU cores is 8
PHP memory_limit is 128M Bytes
Calculated number of workers based on RAM and CPU cores is 32
Maximum number of workers that fit available RAM at memory_limit is 4
Limiting number of workers to 4
```

Performance-M dyno with `--verbose` option:
```
Available RAM is 2560M Bytes
Number of CPU cores is 2
Determining scaling factor based on a memory_limit of 128M
Scaling factor is 5
PHP memory_limit is 128M Bytes
Calculated number of workers based on RAM and CPU cores is 20
```

Container with 4G Bytes RAM and two cores:
```
Available RAM is 4G Bytes
Number of CPU cores is 2
PHP memory_limit is 128M Bytes
Calculated number of workers based on RAM and CPU cores is 20
Maximum number of workers that fit available RAM at memory_limit is 32
Limiting number of workers to 20
```

**Review by edmorley — COMMENTED** [review]
CI is failing

File: bin/util/autotune.php [hunk 1]
```diff
@@ -29,51 +29,60 @@ function bytestostring($amount) {
...
-	exit(2);
+	exit($print_help ? 0 : 2);
 }
 
 $ram = stringtobytes($argv[0]); // first arg is the available memory
 fprintf(STDERR, "Available RAM is %s Bytes\n", bytestostring($ram));
 
 $cores = $argv[1];
-fprintf(STDERR, "Number of CPU cores is %d\n", (int)$cores);
+if($verbose) {
```
Comment (edmorley) [inline bin/util/autotune.php:75]: Isn't this always false? Presuming `1` is falsy?

Even if this is correct as written, it might be clearer to write it using the `>= 1` syntax for parity with the other usages?

Comment (dzuelke) [reply bin/util/autotune.php:75]: No, 1 is always truthy. So `if($verbose)` is for cases that should trigger on any level of verbosity (equivalent to `if($verbose > 0)`); the more explicit checks are for higher levels (of which there is currently only a second one).

Comment (edmorley) [reply bin/util/autotune.php:75]: I think I read this as a bash conditional where exit code non-zero is falsy.

**Comment by jwage** [comment]
Suddenly I am getting this:

```
2024-02-10T02:08:34.086250+00:00 app[web.2]: DOCUMENT_ROOT changed to 'public/'
2024-02-10T02:08:34.144353+00:00 app[web.2]: Using Nginx server-level configuration include 'nginx.conf'
2024-02-10T02:08:34.239393+00:00 app[web.2]: $WEB_CONCURRENCY env var is set, skipping automatic calculation
2024-02-10T02:08:34.254244+00:00 app[web.2]: Starting php-fpm with 4 workers...
2024-02-10T02:08:34.367235+00:00 app[web.2]: Starting nginx...
```

It is on a private-s dyno type with 1024MB of memory.

My public/.user.ini looks like this:

```
memory_limit = 32M
max_execution_time = 20
```

I used to get 32 workers.

I don't have a $WEB_CONCURRENCY environment variable set anywhere in my settings or application.

**Comment by edmorley** [comment]
@jwage Hi! Trying a new app now (which doesn't have `WEB_CONCURRENCY` set), I don't get that output, but instead:

```
2024-02-10T10:14:34.686475+00:00 heroku[web.1]: Starting process with command `heroku-php-apache2 web/`
2024-02-10T10:14:36.346843+00:00 app[web.1]: DOCUMENT_ROOT changed to 'web/'
2024-02-10T10:14:36.521889+00:00 app[web.1]: Available RAM is 512M Bytes
2024-02-10T10:14:36.521911+00:00 app[web.1]: PHP memory_limit is 128M Bytes
2024-02-10T10:14:36.545437+00:00 app[web.1]: Starting php-fpm with 4 workers...
2024-02-10T10:14:36.647751+00:00 app[web.1]: Starting httpd...
2024-02-10T10:14:37.076844+00:00 heroku[web.1]: State changed from starting to up
```

Is it possible you are using another buildpack alongside the PHP buildpack, which is running after the PHP buildpack, and so setting it's own `WEB_CONCURRENCY` value?

**Comment by jwage** [comment]
That is it. I need the PHP buildpack to be first for another reason. I suppose I will set the env variable manually to work around this.
